apps/movies/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.movies.views import SearchFormView, MovieView, ActorView

app_name = 'movies'
urlpatterns = [
    path('search/', SearchFormView.as_view(), name='search-landing'),
    path('search/<str:search>/', SearchFormView.as_view(), name='search'),
    path('movie/<uuid:pk>/', MovieView.as_view(), name='movie-detail'),
    path('actor/<uuid:pk>/', ActorView.as_view(), name='actor-detail'),
]

movieDatabase/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('apps.movies.urls'), name='movies')
]

apps/movies/models.py
from django.db import models
from libs.models import BaseModel


# There can be distinctive movies or actors with the same names!
class Actor(BaseModel):
    name = models.CharField(max_length=255, null=False)
    # For SQLite database, we need to add this field for unicode search,
    unicode_name = models.CharField(max_length=255, null=False, help_text='Unaccented lowercase string for searching')
    date_of_birth = models.DateField(null=True)
    city_of_birth = models.CharField(max_length=255, null=True)

    class Meta:
        unique_together = ('name', 'unicode_name', 'date_of_birth', 'city_of_birth')


class Movie(BaseModel):
    name = models.CharField(max_length=255, null=False)
    year = models.IntegerField(null=False)
    unicode_name = models.CharField(max_length=255, null=False, help_text='Unaccented lowercase string for searching')
    actors = models.ManyToManyField(to=Actor, related_name='movies')

    class Meta:
        unique_together = ('name', 'unicode_name', 'year')

libs/models.py
import uuid
from django.db import models


class BaseModel(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    class Meta:
        abstract = True

apps/movies/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField()

apps/movies/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView
from text_unidecode import unidecode

from apps.movies.forms import SearchForm
from django.views.generic.edit import FormView

from apps.movies.models import Movie, Actor


class SearchFormView(FormView):
    template_name = 'search.html'
    form_class = SearchForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.search:
            context['movies'] = Movie.objects.filter(unicode_name__contains=unidecode(self.search).lower())
            context['actors'] = Actor.objects.filter(unicode_name__contains=unidecode(self.search).lower())
            context['search'] = self.search
        return context

    def get(self, *args, search=None, **kwargs):
        self.search = search
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        return HttpResponseRedirect(reverse('movies:search', kwargs={'search': form.cleaned_data['search']}))


class MovieView(DetailView):
    template_name = 'movie_detail.html'

    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['actors'] = self.object.actors.all()
        return context


class ActorView(DetailView):
    template_name = 'actor_detail.html'

    model = Actor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = self.object.movies.all()
        return context

apps/movies/templates/actor_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.name }}</title>
</head>
<body>
{{ object.name }}: {{ object.date_of_birth }}, {{ object.city_of_birth }}
<div>
    Movies:
    <ul>
        {% for movie in movies %}
            <li><a href={% url 'movies:movie-detail' movie.pk %}> {{ movie.name }} ({{movie.year}})</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

apps/movies/templates/movie_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.name }}</title>
</head>
<body>
{{ object.name }} ({{object.year}})
<div>
    Actors:
    <ul>
        {% for actor in actors %}
            <li><a href={% url 'movies:actor-detail' actor.pk %}> {{ actor.name }}</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

apps/movies/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search your movie!</title>
</head>
<body>
<form action={% url 'movies:search-landing' %} method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% if search %}
    <div>
        Movies
        <ul>
            {% for movie in movies %}
                <li><a href={% url 'movies:movie-detail' movie.pk %}> {{ movie.name }} ({{movie.year}})</a></li>
            {% endfor %}
        </ul>
    </div>
    <div>
        Actors
        <ul>
            {% for actor in actors %}
                <li><a href={% url 'movies:actor-detail' actor.pk %}> {{ actor.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
</body>
</html>